#:kivy 1.10.0
#:import main main

# -*- coding: utf-8 -*-

<MessageBox>:
    title:app.root.getName(app.root.rv_layout.selected_value)
    size_hint: None, None
    size: 280, 205

    GridLayout:
        rows:2
        colums:3
        orientation: 'vertical'
        Label:
            text: 'Tassen:'
        Label:
            text :app.root.getTasse()
        Label:
            text: ''
        Button:
            size_hint: 1, 0.3
            text: 'Tasse'
            on_press: root.dismiss(), app.root.confirmCup(app.root.rv_layout.selected_value)
        Button:
            size_hint: 1, 0.3
            text: 'Kanne'
            on_press: app.root.confirmPot(app.root.rv_layout.selected_value),root.dismiss()
        Button:
            size_hint: 1, .3
            text: 'Abbrechen'
            on_press: root.dismiss()

<SelectableButton>:
    # Draw a background to indicate selection

    canvas.before:
        Color:
            rgba: (0, 0,0,.4)
        Rectangle:
            pos: self.pos
            size: self.size



<RV>:
    rv_layout: layout
    viewclass: 'SelectableButton'
    SelectableRecycleGridLayout:
        id: layout

        default_size: None, 32
        default_size_hint: 0.1, None
        size_hint_y: None
        height: self.minimum_height
        orientation:'horizontal'
        cols:3
